# Generated by Django 4.1.5 on 2023-02-19 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_comment_author_alter_comment_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('datetime_created',)},
        ),
    ]
